version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: job_crawler
      POSTGRES_USER: job_user
      POSTGRES_PASSWORD: job_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U job_user -d job_crawler"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Marqo Vector Database
  marqo:
    image: marqoai/marqo:latest
    container_name: marqo
    ports:
      - "8882:8882"
    restart: unless-stopped
    environment:
      - MARQO_MAX_SEARCHABLE_TENSOR_ATTRIBUTES=20
    volumes:
      - marqo_data:/opt/vespa/var
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8882/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  marqo_data:
